filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: unix:///var/run/docker.sock

output.elasticsearch:
  hosts: ["http://elk-elasticsearch:9200"]
  index: "docker-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://elk-kibana:5601"

logging.level: info