apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  MODEL_PATH: {{ .Values.model.path | quote }}
  MODEL_VERSION: {{ .Values.model.version | quote }}
  RABBITMQ_URL: {{ .Values.infra.rabbitmqUrl | quote }}
  RABBITMQ_QUEUE: "predict_requests"
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.infra.kafkaBootstrap | quote }}
  KAFKA_TOPIC: "predictions.completed"
  REDIS_URL: {{ .Values.infra.redisUrl | quote }}
  POSTGRES_DSN: {{ .Values.infra.postgresDsn | quote }}
  MYSQL_HOST: {{ .Values.infra.mysqlHost | quote }}
  MYSQL_PORT: {{ .Values.infra.mysqlPort | quote }}