apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: ml-service
    component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: ml-service
      component: api
  template:
    metadata:
      labels:
        app: ml-service
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "--timeout", "120", "app:create_app()"]
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}