apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: ml-service
    component: api
spec:
  type: ClusterIP
  selector:
    app: ml-service
    component: api
  ports:
    - name: http
      port: 80
      targetPort: http